version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - set -eux
      - echo "Repo root:" && pwd && ls -la
      - cd "$CODEBUILD_SRC_DIR/fetch_and_filter_data"
      - echo "In fetch_and_filter_data:" && pwd && ls -la
      - test -f fetch_delvered_orders.py 
      - zip -r9 package.zip fetch_delvered_orders.py
      - unzip -l package.zip

  post_build:
    commands:
      - set -eux
      - echo "Verifying absolute path exists..."
      - ls -la "$CODEBUILD_SRC_DIR/fetch_and_filter_data/package.zip"
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code \
          --function-name doordash-datalake-trigger \
          --zip-file "fileb://$CODEBUILD_SRC_DIR/fetch_and_filter_data/package.zip"

